# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaesarCipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=68, null=True)),
                ('decrypt_text', models.TextField()),
                ('encrypt_text', models.TextField()),
                ('keys', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AnswerTypes',
            },
        ),
    ]
